
# I asked ChatGPT4 what the top 5 teaching methods are
METHODS = {
    "Direct Instruction": "This teacher-centered approach involves the instructor providing information, demonstrating concepts, and guiding students through the learning process. It is particularly effective for teaching fundamental skills and factual information.",
    "Inquiry-Based Learning": "In this student-centered approach, teachers encourage students to explore, ask questions, and discover answers by themselves. The teacher acts as a facilitator, guiding students through the process of problem-solving and promoting critical thinking.", 
    "Cooperative Learning": "This method involves students working together in small groups to complete tasks or solve problems. The teacher sets the goals and monitors progress, but students collaborate and learn from each other. This method fosters teamwork, communication, and interpersonal skills.",
    "Project-Based Learning": "Students engage in real-world, complex tasks or projects, working individually or in groups to develop solutions or create products. This method encourages students to apply their knowledge and skills to authentic situations, deepening their understanding and fostering creativity.",
    "Differentiated Instruction":"Recognizing that students have different learning styles, abilities, and interests, teachers provide a variety of instructional strategies and materials to address these differences. This method can include modifying content, process, or product based on the individual needs of each student.",
    "Socratic Instruction": "The teacher serves as a facilitator who guides the conversation and promotes deeper understanding by posing open-ended questions, often about complex or abstract concepts. Instead of providing direct answers, the teacher encourages students to think critically, analyze their assumptions, and synthesize information to arrive at their conclusions."
}